### PR TITLE
Fix: code quality issues

### PR DESCRIPTION
**Pull request by ankitdobhal**
# Description
Hi 👋 I ran the [DeepSource](https://deepsource.io/) static analyzer on the forked copy of this repo and found some [interesting code quality issues](https://deepsource.io/gh/ankitdobhal/Scrython/issues/). This PR fixes a few of them.

## Summary of changes :
 - Removed unused imports
 - fixed the not in statement
 - Removed reimported modules
 - added .deepsource.toml file

### CODE REVIEW

**Comment by ankitdobhal** [comment]
@NandaScott kindly review the PR.

**Comment by NandaScott** [comment]
Thank you for submitting this PR. I will look more into this, and overall the removal of imports is good.

**Comment by ankitdobhal** [comment]
> Thank you for submitting this PR. I will look more into this, and overall the removal of imports is good.

@NandaScott Thanks for response.

**Comment by NandaScott** [comment]
Hi, my apologies for this late reply. I don't always have the time to sit down with this project.

I appreciate the code quality updates, but I don't think this project really needs the DeepSource integration.

**Pull request closed without merging**
