### PR TITLE
Make Scryfall errors easier to catch and handle

### PR DESCRIPTION
**Pull request by vtbassmatt**
This change would make Scryfall errors catchable and easier to handle. For one, it adds a unique exception type. And it also copies over the [Error object](https://scryfall.com/docs/api/errors) details, allowing a machine to handle things like the different 404s.

### CODE REVIEW

**Comment by NandaScott** [comment]
Hey thanks for the PR! I'm currently busy but I'll take a look at this tonight.

**Comment by vtbassmatt** [comment]
No worries, thanks for the library!

**Comment by vtbassmatt** [comment]
I also just noticed a big bug, since I wrote it on GitHub and didn't actually test it out. Will fix.

**Comment by NandaScott** [comment]
I'm trying out your branch to test it but I'm `ScryfallError` is throwing this:

```
Traceback (most recent call last):
  File "./handle_errors.py", line 6, in <module>
    search = scrython.cards.Search(q="!Black Lotus")
  File "/mnt/g/Coding/Scrython/scrython/cards/search.py", line 77, in __init__
    super(Search, self).__init__(self.url)
  File "/mnt/g/Coding/Scrython/scrython/foundation.py", line 38, in __init__
    raise ScryfallError(self.scryfallJson, message=self.scryfallJson['details'])
  File "/mnt/g/Coding/Scrython/scrython/foundation.py", line 7, in __init__
    super(self.__class__, self).__init__(*args, **kwargs)
TypeError: ScryfallError() takes no keyword arguments
```

My python is kinda rusty, but it doesn't seem like it should do that. Any ideas?

**Comment by vtbassmatt** [comment]
🤦‍♂ After I said I was going to test this locally, I got distracted and didn't. Fixed the super obvious, super silly bugs.

image

**Comment by NandaScott** [comment]
Not sure why your implementation works and mine didn't. I had to do the following to get it to work.

image

**Comment by vtbassmatt** [comment]
I had made a mistake not only in how I construct the error (`Exception` doesn't take a `message` parameter), but also in the example. I didn't mean to put those fields directly on the exception object, I just meant to copy over the dict from the Scryfall error body. Did you try my updated example?

**Comment by NandaScott** [comment]
Oh I messed up. I see that your updated example would work. I think these changes would be fine. I'll merge it into `develop` instead of `master`.

**Pull request merged**
